#!/usr/bin/env python3
"""
Generate code-server config.yaml.

By default this will:
- bind code-server to 0.0.0.0:<port> (port from .env.toml [code_server].port)
- enable password auth (password provided via systemd env PASSWORD)
- point to cert/key generated by gen_self_signed_cert.py in [cert].out_dir

Configuration precedence (highest first):
1. CLI arguments: --bind-host / --port / --out-dir
2. .env.toml:
   - [code_server].bind_host
   - [code_server].port
   - [cert].out_dir
3. Built-in defaults:
   bind_host = 0.0.0.0
   port      = 8080
   out_dir   = ~/.config/code-server
"""

import argparse
import os
from pathlib import Path
import sys


def load_env_toml(path: Path) -> dict:
    """Load a TOML config file if it exists, otherwise return {}."""
    try:
        import tomllib  # Python 3.11+
    except ImportError:  # pragma: no cover
        try:
            import tomli as tomllib  # type: ignore
        except ImportError:
            return {}

    if not path.is_file():
        return {}

    try:
        with path.open("rb") as f:
            return tomllib.load(f)
    except Exception as exc:  # pragma: no cover
        print(f"[WARN] Failed to parse {path}: {exc}", file=sys.stderr)
        return {}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate code-server config.yaml"
    )
    parser.add_argument(
        "--bind-host",
        dest="bind_host",
        default=None,
        help="Host part for bind-addr (default: from .env.toml [code_server].bind_host or 0.0.0.0)",
    )
    parser.add_argument(
        "--port",
        dest="port",
        type=int,
        default=None,
        help="Port for bind-addr (default: from .env.toml [code_server].port or 8080)",
    )
    parser.add_argument(
        "--out-dir",
        dest="out_dir",
        default=None,
        help="Directory where cert.pem/key.pem and config.yaml live "
        "(default: from .env.toml [cert].out_dir or ~/.config/code-server)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing config.yaml if it exists.",
    )
    parser.add_argument(
        "--env-file",
        dest="env_file",
        default=None,
        help="Path to TOML config file (default: ../.env.toml relative to script).",
    )

    args = parser.parse_args()

    # Resolve env file path
    if args.env_file:
        env_path = Path(args.env_file).expanduser()
    else:
        repo_root = Path(__file__).resolve().parents[1]
        env_path = repo_root / ".env.toml"

    env_cfg = load_env_toml(env_path)
    code_cfg = env_cfg.get("code_server", {}) if isinstance(env_cfg, dict) else {}
    cert_cfg = env_cfg.get("cert", {}) if isinstance(env_cfg, dict) else {}

    bind_host = args.bind_host or code_cfg.get("bind_host") or "0.0.0.0"
    port = args.port or code_cfg.get("port") or 8080
    out_dir_val = args.out_dir or cert_cfg.get("out_dir") or "~/.config/code-server"

    out_dir = os.path.expanduser(out_dir_val)
    os.makedirs(out_dir, exist_ok=True)

    config_path = os.path.join(out_dir, "config.yaml")
    cert_path = os.path.join(out_dir, "cert.pem")
    key_path = os.path.join(out_dir, "key.pem")

    if not args.force and os.path.exists(config_path):
        print(
            f"[ERROR] {config_path} already exists.\n"
            "Use --force to overwrite existing file.",
            file=sys.stderr,
        )
        raise SystemExit(1)

    content = (
        f"bind-addr: {bind_host}:{port}\n"
        f"auth: password\n"
        f"cert: {cert_path}\n"
        f"cert-key: {key_path}\n"
    )

    with open(config_path, "w", encoding="utf-8") as f:
        f.write(content)

    if env_cfg:
        print(f"[INFO] Using env file: {env_path}")
    else:
        print("[INFO] No env file found, using CLI/default values.")

    print(f"[OK] Wrote code-server config to {config_path}")
    print(f"     bind-addr: {bind_host}:{port}")
    print(f"     cert     : {cert_path}")
    print(f"     cert-key : {key_path}")


if __name__ == "__main__":
    main()

